<dl>
<?php
  echo "  <dt>Razón Social:</dt> <dd>$DAO->razonsocial</dd>\n";
  echo "  <dt>RFC:</dt> <dd>$DAO->rfc</dd>\n";
  echo "  <dt>Dirección:</dt> <dd>$DAO->direccion</dd>\n";
  echo "  <dt>Ciudad, Estado:</dt> <dd>$DAO->colonia</dd>\n";
  echo "  <dt>Código Postal:</dt> <dd>$DAO->cp</dd>\n";  
  echo "  <dt>Telefono:</dt> <dd>$DAO->telefono</dd>\n";
  
?>
</dl>
<?php if(!$lectura) { ?>
<input type="button" onclick="xajax_editarFactura(<?php echo $id_pago ?>)" value="Editar"/>
<input type="button" onblur="xajax_eliminarFactura(<?php echo $DAO->getId() ?>)" value="Eliminar"/>
<?php }?>