<?php echo "<strong>".$DAO->getDescr()."</strong>: $DAO->no_personas personas x $DAO->no_noches noches x $".$DAO->getCosto()." = \$" . $DAO->no_personas * $DAO->no_noches * $DAO->getCosto(); ?>
<?php if(!$lectura) { ?>
  <input type="button" onclick="xajax_editarHospedaje('<?php echo $DAO->getId()?>', '<?php echo $DAO->id_pago?>')" value="Editar"/>
  <input type="button" onclick="xajax_eliminarHospedaje('<?php echo $DAO->getId()?>')" value="Eliminar"/>
<?php }?>