<?php extract($data);?>
<form action="" id="asistente_form">
<p>
	<input type="hidden" name="id" id="id" value="<?php echo $id?>"/>
	<label for="nombrep">Nombre:*</label><input type="text" size="30" name="nombrep" id="nombrep" value="<?php echo $nombrep ?>"/>
	<label for="apellidos">Apellidos:*</label><input type="text" size="30"name="apellidos" id="apellidos" value="<?php echo $apellidos ?>"/><br/>
	<label for="mail">Correo:*</label><input type="text" size="30" name="mail" id="mail" value="<?php echo $mail ?>"/>
	<?php echo FormHelper::createRadio('Sexo:*', 'sexo', array('M'=>'Masculino','F'=>'Femenino'), $sexo, 'M'); ?><br/>	
	<?php echo FormHelper::createSelect('Estudios:*', 'id_estudios', $estudios, $id_estudios); ?>
	<?php echo FormHelper::createSelect('Estado:*', 'id_estado', $estados, $id_estado); ?>
	<label for="ciudad">Ciudad:</label><input type="text" size="30" name="ciudad" id="ciudad" value="<?php echo $ciudad ?>"/>
	<?php echo FormHelper::createSelect('Edad:*', 'edad', $edades, $edad, 0); ?><br/>
	<hr/>
	<input type="button" onclick="parent.location='admin.php?opc=20&amp;tab=0'" value="Cancelar"/>
	<input type="button" onclick="xajax_guardarContinuar(xajax.getFormValues('asistente_form'))" value="Guardar y Continuar"/>
</p>
</form>