<?
include "conf.inc";

print '
</td></tr></table><br><br>
<table border=0 cellpading=0 cellspacing=0 width=100%>
<tr><td bgcolor=#5F6B8B>
<table border=0 cellpading=1 cellspacing=1 width=100%>
<tr><td bgcolor=#FFFFFF>
<center><font face=arial size=-2>
Copyright(c) 
<a href="http://patux.glo.org.mx/">
Geronimo Orozco
</a>
<br>
</font><br><br>
<a href="http://php.net">
<img src="'.$rootpath.'/images/php-small-trans-light.gif" border=0></a>
<a href="http://mysql.com">
<img src="'.$rootpath.'/images/workswithmysql.jpg" border=0></a>
<a href="http://www.vim.org">
<img src="'.$rootpath.'/images/anim_written_in_vi.gif" border=0></a><br>
</center>
</td></tr>
</table>
</td></tr>
</table></body></html>';
?>
