<?
include "conf.inc";

print '
</td></tr></table><br><br>
<table border=0 cellpading=0 cellspacing=0 width=100%>
<tr><td bgcolor=#911f43>
<table border=0 cellpading=1 cellspacing=1 width=100%>
<tr><td bgcolor=#FFFFFF>
<center><font face=arial size=-2>
Copyright(c) 
<a href="http://glo.org.mx/~patux/">
Yacomas Development team
</a>
<br>
</font><br><br>
<a href="http://php.net">
<img src="'.$rootpath.'/images/php-small-trans-light.gif" border=0></a>
<a href="http://mysql.com">
<img src="'.$rootpath.'/images/workswithmysql.jpg" border=0></a>
<a href="http://www.vim.org">
<img src="'.$rootpath.'/images/anim_written_in_vi.gif" border=0></a><br>
<center>
</td></tr>
</table>
</td></tr>
</table></body></html>';
?>
